# Python stubs generated by omniidl from Connexion_manager.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Connexion_manager"
#
__name__ = "Connexion_manager"
_0_Connexion_manager = omniORB.openModule("Connexion_manager", r"Connexion_manager.idl")
_0_Connexion_manager__POA = omniORB.openModule("Connexion_manager__POA", r"Connexion_manager.idl")


# interface Order
_0_Connexion_manager._d_Order = (omniORB.tcInternal.tv_objref, "IDL:Connexion_manager/Order:1.0", "Order")
omniORB.typeMapping["IDL:Connexion_manager/Order:1.0"] = _0_Connexion_manager._d_Order
_0_Connexion_manager.Order = omniORB.newEmptyClass()
class Order :
    _NP_RepositoryId = _0_Connexion_manager._d_Order[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Connexion_manager.Order = Order
_0_Connexion_manager._tc_Order = omniORB.tcInternal.createTypeCode(_0_Connexion_manager._d_Order)
omniORB.registerType(Order._NP_RepositoryId, _0_Connexion_manager._d_Order, _0_Connexion_manager._tc_Order)

# Order operations and attributes
Order._d_execute = ((), (), None)

# Order object reference
class _objref_Order (CORBA.Object):
    _NP_RepositoryId = Order._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def execute(self, *args):
        return self._obj.invoke("execute", _0_Connexion_manager.Order._d_execute, args)

omniORB.registerObjref(Order._NP_RepositoryId, _objref_Order)
_0_Connexion_manager._objref_Order = _objref_Order
del Order, _objref_Order

# Order skeleton
__name__ = "Connexion_manager__POA"
class Order (PortableServer.Servant):
    _NP_RepositoryId = _0_Connexion_manager.Order._NP_RepositoryId


    _omni_op_d = {"execute": _0_Connexion_manager.Order._d_execute}

Order._omni_skeleton = Order
_0_Connexion_manager__POA.Order = Order
omniORB.registerSkeleton(Order._NP_RepositoryId, Order)
del Order
__name__ = "Connexion_manager"

# interface Connexion_client
_0_Connexion_manager._d_Connexion_client = (omniORB.tcInternal.tv_objref, "IDL:Connexion_manager/Connexion_client:1.0", "Connexion_client")
omniORB.typeMapping["IDL:Connexion_manager/Connexion_client:1.0"] = _0_Connexion_manager._d_Connexion_client
_0_Connexion_manager.Connexion_client = omniORB.newEmptyClass()
class Connexion_client :
    _NP_RepositoryId = _0_Connexion_manager._d_Connexion_client[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Connexion_manager.Connexion_client = Connexion_client
_0_Connexion_manager._tc_Connexion_client = omniORB.tcInternal.createTypeCode(_0_Connexion_manager._d_Connexion_client)
omniORB.registerType(Connexion_client._NP_RepositoryId, _0_Connexion_manager._d_Connexion_client, _0_Connexion_manager._tc_Connexion_client)

# Connexion_client operations and attributes
Connexion_client._d_list_modules = ((), ((omniORB.tcInternal.tv_string,0), ), None)
Connexion_client._d_execute_order = ((omniORB.typeMapping["IDL:Connexion_manager/Order:1.0"], ), (), None)

# Connexion_client object reference
class _objref_Connexion_client (CORBA.Object):
    _NP_RepositoryId = Connexion_client._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def list_modules(self, *args):
        return self._obj.invoke("list_modules", _0_Connexion_manager.Connexion_client._d_list_modules, args)

    def execute_order(self, *args):
        return self._obj.invoke("execute_order", _0_Connexion_manager.Connexion_client._d_execute_order, args)

omniORB.registerObjref(Connexion_client._NP_RepositoryId, _objref_Connexion_client)
_0_Connexion_manager._objref_Connexion_client = _objref_Connexion_client
del Connexion_client, _objref_Connexion_client

# Connexion_client skeleton
__name__ = "Connexion_manager__POA"
class Connexion_client (PortableServer.Servant):
    _NP_RepositoryId = _0_Connexion_manager.Connexion_client._NP_RepositoryId


    _omni_op_d = {"list_modules": _0_Connexion_manager.Connexion_client._d_list_modules, "execute_order": _0_Connexion_manager.Connexion_client._d_execute_order}

Connexion_client._omni_skeleton = Connexion_client
_0_Connexion_manager__POA.Connexion_client = Connexion_client
omniORB.registerSkeleton(Connexion_client._NP_RepositoryId, Connexion_client)
del Connexion_client
__name__ = "Connexion_manager"

#
# End of module "Connexion_manager"
#
__name__ = "Connexion_manager_idl"

_exported_modules = ( "Connexion_manager", )

# The end.
