# DO NOT EDIT THIS FILE!
#
# Python module Connexion_manager__POA generated by omniidl

import omniORB
omniORB.updateModule("Connexion_manager__POA")

# ** 1. Stub files contributing to this module
import Connexion_manager_idl

# ** 2. Sub-modules

# ** 3. End
